<?
	define("LTChat_Main_CHAT_ID","0");
	define("LTChat_Main_lang","english");
	define("LTChat_Main_datasource","mysql");
	define("LTChat_Main_scriptpath","");
	define("LTChat_Main_dbhost","localhost");
	define("LTChat_Main_dbname","chat");
	define("LTChat_Main_dbuser","root");
	define("LTChat_Main_dbpassword","");
	define("LTChat_Main_prefix","");
?>